# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 443)
        Form.setStyleSheet("QWidget#Form {\n"
"    background-color: #040c0e;\n"
"}\n"
"QFrame#frame, QFrame#frame_2 {\n"
"    background-color: #040c0e;\n"
"    border: 2px solid #be9063;\n"
"    border-radius: 20px;\n"
"}\n"
"QWidget#scrollAreaWidgetContents {\n"
"    background-color: #040c0e;\n"
"}\n"
"QScrollArea {\n"
"    border-color: #040c0e;\n"
"}\n"
"QPushButton {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 2)
        self.max_date = QtWidgets.QLabel(self.frame)
        self.max_date.setObjectName("max_date")
        self.gridLayout_2.addWidget(self.max_date, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.mark_frame = QtWidgets.QFrame(self.frame)
        self.mark_frame.setMaximumSize(QtCore.QSize(30, 30))
        self.mark_frame.setStyleSheet("background-color: #be9063;\n"
"border-radius: 5px;\n"
"")
        self.mark_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mark_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mark_frame.setObjectName("mark_frame")
        self.gridLayout_2.addWidget(self.mark_frame, 2, 3, 1, 1)
        self.comment_lbl = QtWidgets.QLabel(self.frame)
        self.comment_lbl.setObjectName("comment_lbl")
        self.gridLayout_2.addWidget(self.comment_lbl, 5, 0, 1, 4)
        self.max_cat_lbl = QtWidgets.QLabel(self.frame)
        self.max_cat_lbl.setObjectName("max_cat_lbl")
        self.gridLayout_2.addWidget(self.max_cat_lbl, 1, 1, 1, 3)
        self.max_lbl = QtWidgets.QLabel(self.frame)
        self.max_lbl.setObjectName("max_lbl")
        self.gridLayout_2.addWidget(self.max_lbl, 0, 1, 1, 3)
        self.cost_max_date = QtWidgets.QLabel(self.frame)
        self.cost_max_date.setObjectName("cost_max_date")
        self.gridLayout_2.addWidget(self.cost_max_date, 3, 2, 1, 1)
        self.ess_to_lbl = QtWidgets.QLabel(self.frame)
        self.ess_to_lbl.setObjectName("ess_to_lbl")
        self.gridLayout_2.addWidget(self.ess_to_lbl, 2, 1, 1, 2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font-size: 40px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Самый дорогой день:"))
        self.max_date.setText(_translate("Form", "-"))
        self.label_2.setText(_translate("Form", "Всего потрачено"))
        self.label_3.setText(_translate("Form", "Больше всего на:"))
        self.label_4.setText(_translate("Form", "Отношение обязательных  необязательным:"))
        self.comment_lbl.setText(_translate("Form", "Комментарий:"))
        self.max_cat_lbl.setText(_translate("Form", "-"))
        self.max_lbl.setText(_translate("Form", "-"))
        self.cost_max_date.setText(_translate("Form", "-"))
        self.ess_to_lbl.setText(_translate("Form", "-"))
        self.label.setText(_translate("Form", "Краткая сводка"))
