# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(614, 398)
        MainMenu.setStyleSheet("QMainWindow {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"}\n"
"QLabel:hover {\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #F3E0D2;\n"
"}\n"
"QPushButton {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"    border-radius: 12px;\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    opacity: 0.6;\n"
"    padding: 5px\n"
"}\n"
"QFrame#frame, QFrame#frame_2 {\n"
"    background-color: #040c0e;\n"
"    border: 2px solid #be9063;\n"
"    border-radius: 20px;\n"
"}\n"
"QLabel#login_label, QLabel#password_label {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 30px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #525b56;\n"
"}\n"
"QPushButton#remember_btn:checked {\n"
"    background-color: #be9063;\n"
"    color: #040c0e;\n"
"}\n"
"QPushButton#add_btn:hover {\n"
"    background-color: rgba(59, 200, 34, 200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.settings_btn = QtWidgets.QPushButton(self.frame_3)
        self.settings_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.settings_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.settings_btn.setText("")
        self.settings_btn.setObjectName("settings_btn")
        self.gridLayout_3.addWidget(self.settings_btn, 0, 2, 1, 1)
        self.exit_btn = QtWidgets.QPushButton(self.frame_3)
        self.exit_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.exit_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(40, 40))
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout_3.addWidget(self.exit_btn, 0, 3, 1, 1)
        self.username_lbl = QtWidgets.QLabel(self.frame_3)
        self.username_lbl.setMinimumSize(QtCore.QSize(0, 35))
        self.username_lbl.setObjectName("username_lbl")
        self.gridLayout_3.addWidget(self.username_lbl, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 4)
        self.add_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setMinimumSize(QtCore.QSize(90, 90))
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon1)
        self.add_btn.setIconSize(QtCore.QSize(60, 60))
        self.add_btn.setObjectName("add_btn")
        self.gridLayout_2.addWidget(self.add_btn, 1, 0, 2, 3)
        self.graphs_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphs_btn.sizePolicy().hasHeightForWidth())
        self.graphs_btn.setSizePolicy(sizePolicy)
        self.graphs_btn.setMinimumSize(QtCore.QSize(90, 90))
        self.graphs_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphs_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/icons/stats.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphs_btn.setIcon(icon2)
        self.graphs_btn.setIconSize(QtCore.QSize(60, 60))
        self.graphs_btn.setObjectName("graphs_btn")
        self.gridLayout_2.addWidget(self.graphs_btn, 1, 3, 1, 1)
        self.payments_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payments_btn.sizePolicy().hasHeightForWidth())
        self.payments_btn.setSizePolicy(sizePolicy)
        self.payments_btn.setMinimumSize(QtCore.QSize(90, 90))
        self.payments_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.payments_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payments_btn.setIcon(icon3)
        self.payments_btn.setIconSize(QtCore.QSize(60, 60))
        self.payments_btn.setObjectName("payments_btn")
        self.gridLayout_2.addWidget(self.payments_btn, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Меню"))
        self.username_lbl.setText(_translate("MainMenu", "username"))
