# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_reg_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegWindow(object):
    def setupUi(self, RegWindow):
        RegWindow.setObjectName("RegWindow")
        RegWindow.resize(743, 299)
        RegWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"}\n"
"QLabel:hover {\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #F3E0D2;\n"
"}\n"
"QPushButton {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"    border-radius: 12px;\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    opacity: 0.6;\n"
"    padding: 5px\n"
"}\n"
"QFrame#frame, QFrame#frame_2 {\n"
"    background-color: #040c0e;\n"
"    border: 2px solid #be9063;\n"
"    border-radius: 20px;\n"
"}\n"
"QLabel#login_label, QLabel#password_label {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 30px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #525b56;\n"
"}\n"
"QPushButton#remember_btn:checked {\n"
"    background-color: #be9063;\n"
"    color: #040c0e;\n"
"}\n"
"QPushButton#add_btn:hover {\n"
"    background-color: rgba(59, 200, 34, 200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(RegWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.reg_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_btn.setObjectName("reg_btn")
        self.horizontalLayout_2.addWidget(self.reg_btn)
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_2.addWidget(self.login_btn)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(700, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.login_le = QtWidgets.QLineEdit(self.frame)
        self.login_le.setMinimumSize(QtCore.QSize(50, 0))
        self.login_le.setObjectName("login_le")
        self.gridLayout.addWidget(self.login_le, 1, 1, 1, 1)
        self.password_le = QtWidgets.QLineEdit(self.frame)
        self.password_le.setMinimumSize(QtCore.QSize(50, 0))
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setObjectName("password_le")
        self.gridLayout.addWidget(self.password_le, 2, 1, 1, 1)
        self.login_label = QtWidgets.QLabel(self.frame)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 1, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.frame)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 2, 0, 1, 1)
        self.remember_btn = QtWidgets.QPushButton(self.frame)
        self.remember_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.remember_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remember_btn.setCheckable(True)
        self.remember_btn.setChecked(False)
        self.remember_btn.setObjectName("remember_btn")
        self.gridLayout.addWidget(self.remember_btn, 3, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 3, 1, 1, 1)
        RegWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegWindow)
        self.statusbar.setObjectName("statusbar")
        RegWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegWindow)
        QtCore.QMetaObject.connectSlotsByName(RegWindow)

    def retranslateUi(self, RegWindow):
        _translate = QtCore.QCoreApplication.translate
        RegWindow.setWindowTitle(_translate("RegWindow", "Авторизация"))
        self.label.setText(_translate("RegWindow", "Авторизация"))
        self.reg_btn.setText(_translate("RegWindow", "зарегистрироваться"))
        self.login_btn.setText(_translate("RegWindow", "войти"))
        self.login_label.setText(_translate("RegWindow", "Логин"))
        self.password_label.setText(_translate("RegWindow", "Пароль"))
        self.remember_btn.setText(_translate("RegWindow", "запомнить"))
